version: '2'
services:

  my_magento_eshop_awslogs:
    mem_limit: 134217728
    image: 137115356293.dkr.ecr.eu-west-1.amazonaws.com/my_magento_eshop_awslogs:latest

  my_magento_eshop_appcode:
    mem_limit: 134217728
    image: 137115356293.dkr.ecr.eu-west-1.amazonaws.com/my_magento_eshop_appcode:latest
    depends_on:
      - my_magento_eshop_awslogs
    volumes_from:
      - my_magento_eshop_awslogs
    volumes:
      - /mnt/efs.mounts/ecs_common/services/my_magento_eshop/env/integration/magento/media:/var/www/magento/media

  my_magento_eshop_phpfpm:
    mem_limit: 134217728
    image: 137115356293.dkr.ecr.eu-west-1.amazonaws.com/my_magento_eshop_phpfpm:latest
    restart: always
    depends_on:
      - my_magento_eshop_appcode
      - my_magento_eshop_awslogs
    volumes_from:
      - my_magento_eshop_appcode
      - my_magento_eshop_awslogs

  my_magento_eshop_nginx:
    mem_limit: 134217728
    image: 137115356293.dkr.ecr.eu-west-1.amazonaws.com/my_magento_eshop_nginx:latest
    restart: always
    depends_on:
      - my_magento_eshop_appcode
      - my_magento_eshop_awslogs
      - my_magento_eshop_phpfpm
    volumes_from:
      - my_magento_eshop_appcode
      - my_magento_eshop_awslogs
    links:
      - my_magento_eshop_phpfpm
    ports:
      - "80"
